apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-for-proposal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: request-for-proposal
  template:
    metadata:
      labels:
        app: request-for-proposal
    spec:
      containers:
      - name: request-for-proposal
        image: myrepo/request-for-proposal:latest
        ports:
        - containerPort: 3002
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
