apiVersion: v1
kind: Service
metadata:
  name: request-for-proposal-service
  labels:
    app: request-for-proposal
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: request-for-proposal