apiVersion: v1
kind: Service
metadata:
  name: users-management-service
  labels:
    app: users-management
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: users-management